@types/index.ts, README.md, src/layouts/basic5e.ts, src/main.ts, src/watcher/watcher.worker.ts
closes #14 
Added bonus_actions to the StatblockParameters type.
Added bonus_actions to the postprocessor trait cleanup block.
Added bonus_actions to the basic5e StatblockItem array.
Added bonus_actions to the parseFileForCreatures function in watcher.worker.
Added bonus_actions to the README example.
=> Added Support for "Bonus Actions" trait

src/data/constants.ts, src/importers/5eToolsImport.ts, src/view/ui/Spells.svelte, src/view/ui/Traits.svelte
Hi,
i've tried to import characters from 5e and found some small problems
- some template code was left untouched
- AC for some creatures wasn't extracted
- for some creatures that has both 'spellcasting' and 'innate spellcasting' only first block rendered in statblock
this pr is trying to fix them
for the last clause probably should be better solution, at the moment i render trait without name, for the second spellcasting block, something like this:
=> Fix 5e tools import and multi spell trait support

.gitignore, src/view/ui/MarkdownHolder.svelte
Force display inline when rendering a block as markdown
See issue #60
=> Fix markdown holder styling

src/importers/5eToolsImport.ts, src/importers/ImprovedInitiativeImport.ts
fixed #70 
EDIT: added bonus action importing for improved initiative tracker too. Looks like all the rest of the sites/databases importing is implemented for either doesn't support bonus actions as their own section (they use traits for that) or don't have any monsters to import that have bonus actions
=> Bonus action importing

.gitignore, src/layouts/types.ts, src/settings/ui/block.ts, src/view/ui/Subheading.svelte
By default, the subheading properties are separated with just a space. I just added a text field in the subheading block to enter a different separator. By default it's locked to this:
with no ability to change it (short of changing the code). With this, you can set it to " / ", ", " " | ", etc. Anything should work. Example:
Added data.json to .gitignore because it kept showing up and wouldn't go away, lmk if this needs to be removed.
=> Custom separator for subheading properties

@types/index.ts, src/data/srd-bestiary.ts, src/importers/5eToolsImport.ts, src/layouts/basic5e.ts, src/layouts/types.ts, src/main.ts, src/settings/settings.ts, src/settings/ui/block.ts, src/util/util.ts, src/view/ui/PropertyLine.svelte, src/view/ui/Table.svelte
Added #48 and #57
Fixed #67 and #78 
This is only a half fix for #78. This only adds the footerEntries of _some_ of the 5eTools monsters. The ones with footerEntries in variants were not added (though I believe variants are already not supported anyways).
=> Custom logic for stat mod calculations + Disabling SRD monsters + False statements in Property Line + footerEntries from 5etools

src/main.ts
Markdown-style links in statblock codeblocks would not get picked up during rendering:
The regex to search for links has been updated to include markdown-style links:
Note: I did not update the changelog
=> Adds support for markdown-style links in statblock codeblocks

src/layouts/pathfinder 2e/Basic Pathfinder 2e Layout.json, src/layouts/pathfinder 2e/pf2e.css, src/layouts/pathfinder 2e/pf2e.ts
1. Removed unnecessary boxes in layout preparation for layout overhaul in 1.6. Rendering should be slightly faster.
2. Added "token" YAML key for images. token will automatically reverse the image and be located near the end of the statblock.
3. Added attached text block for token YAML key, so Image Window can be used with the image links. 
4. Added more static items to in-file sass variables to reduce the amount of items needed in dash variables.
5. Fixed popovers with blocklinks.
6. Snippet size is now at ~3450 lines.
I included the regular Layout export.. just in case I messed up the pf2e.ts merge as its my first time doing it. :)
=> Pathfinder 1.5 CSS and Layout Update

package-lock.json, package.json, src/importers/DnDAppFilesImport.ts
Currently, `fantasy-statblocks` has a [direct dependency](https://github.com/valentine195/fantasy-statblocks/blob/master/package-lock.json#L10439) on v0.6.0 of the `xmldom` package.
This is a problem because this package contains two known, notable security vulnerabilities:
* [Critical severity – xmldom allows multiple root nodes in a DOM](https://github.com/advisories/GHSA-crh6-fp67-6883)
* [Moderate severity – Misinterpretation of malicious XML input](https://github.com/advisories/GHSA-5fg8-2547-mr8q)
This is also a problem because, as of v0.7.0, [this package](https://www.npmjs.com/package/@xmldom/xmldom) is published to npm as `@xmldom/xmldom` and no longer as `xmldom`. According to the package's maintainers, they are [no longer able to …
=> Upgrade xmldom to v0.7.10, fixing two security vulnerabilities

src/settings/ui/block.ts, src/view/ui/Subheading.svelte, types/layout.ts
Separator in Subheading block was not working correctly. Anything written in it was ignored and default value (" ") was used.
1. Changed separator from optional value to mandatory value (Reason: when using parameter in join, it takes any string passed on)
2. item.Separator in view was never null
3. Deleted invalid if from Subheading modal 
BEGIN_COMMIT_OVERRIDE
fix: Respect subheading separator in layouts
END_COMMIT_OVERRIDE
=> Fixed not working Separator in Subheading block

src/importers/5eToolsImport.ts
5e.tools stores monster subtypes in tags.  This PR adds a function to extract subtypes from these tags and add them to the subtype property.
- Add `getSubType` function to extract subtypes from 5e.tools tags
N/A
N/A
N/A
BEGIN_COMMIT_OVERRIDE
feat: Extract monster subtypes from 5e.tools tags
END_COMMIT_OVERRIDE
=> Extract monster subtypes from 5e.tools tags

src/view/Statblock.svelte
Currently working on adding support for this plugin with my theme and stumbled into this issue.
statblocks sets a css variable called `---statblock-heading-font-color` however it doesn't seem to be used when settting the `--active--heading-font-color`
we don't lose any existing functionality or break existing styles as  `--statblock-heading-font-color` defaults to  `--statblock-font-color` which defaults to `--statblock-primary-color`. this mimics the functionality that `--active-font-color` has as well.
**src/main.css**
```
--statblock-primary-color: #7a200d;
[ ... ]
--statblock-font-color: var(--statblock-primary-color);
[ ... ]
--statblock-heading-font-color: var(--statblock-font-color);
```
**src/view/Statblock.svelte**
```
--active--font-color: var(
--statblock-font-color, …
```
=> refactor(css): seperate active-heading-font-color from active-font-color

src/view/Statblock.svelte, src/view/ui/Traits.svelte
after #366 was merged I noticed a few other discrepancies so decided to handle them as well.
N/A
**Property name use css variable changes**
```
:root {
--statblock-property-name-font-color: var(--dark0);
}
```
|      Before         |         After       |
|---------------------|---------------------|
| ![property-name-before](https://github.com/javalent/fantasy-statblocks/assets/44450112/699e1d15-9955-40fa-b111-28cf79e7e9fa) | ![property-name-after](https://github.com/javalent/fantasy-statblocks/assets/44450112/e6aff2ad-5598-492d-9a25-e033082a48be) |
**Trait property name changes**
```
:root {
--statblock-property-name-font-color: var(--dark0);
}
```
|      Before         |         After       |
|---------------------|---------------------|
| …
=> fix(css): add consistency to css variables for statblocks

src/view/ui/Traits.svelte
Allows markdown formatting in trait names. This gives more freedom to layout authors.
- Change the `TextContent` in `Traits.svelte` to a `TextContentHolder`
Fixes #428
=> feat: Allow markdown formatting in trait names (close #428)

src/settings/layout/blocks/ui/block.ts, src/view/ui/Traits.svelte
This allows layout authors to write custom callbacks which can refer back to the trait for that callback. With the current implementation, the callback has access to the monster, but no reference to the current trait being rendered, which makes the utility very limited (eg every trait description would be the same)
I didn't make a feature request for this one. Let me know if you'd like me to.
As far as I can tell this shouldn't break any existing layouts. The only potential issue I can think of is if any existing layouts use the `property` variable in a trait callback, but I think in that case it would actually just get locally overridden - but I'm not 100% sure and haven't checked as it seems like a very edge case.
=> feat: Pass the current property as a parameter for trait callbacks

src/layouts/pathfinder 2e/xCSS/pf2e.css
When using the plugin on iOS with Pathfinder 2e, the action icons in the bestiary community content, which are ⬽ or similar in the descriptions, don't render using the "Pathfinder" icon font as they do on Windows. This is because the system-ui font takes precedence, and on iOS that font includes these icons.
Obsidian-TTRPG-Community/Fantasy-Statblocks-CSS-Development#10
| Before | After |
| -------- | ------- |
|  ![Before](https://github.com/javalent/fantasy-statblocks/assets/21015774/3833143d-4790-419d-923d-130893e47602) | ![After](https://github.com/javalent/fantasy-statblocks/assets/21015774/671201b7-9c71-44f9-a25c-1ea2ecfd0b9f) |
N/A
=> fix(css): prioritize pf2e icons over system font

src/importers/TetraCubeImport.ts
Update the importer from TetraCube to include subtype, bonus actions, mythic actions, lair actions, and regional effects.
The purpose of the pull request is to update the TetraCube importer to include missing elements.
Fixes #316
=> Update TetraCube Importing (Fix for Issue #316 included)

src/parser/stringifier.ts
The previous regex would match the following:
```
abilityMods: [4, 2, 3, -3, 1, -1]
resistances: "[Some Link](note.md)"
```
So that that the first group (the link text) would match:
```
4, 2, 3, -3, 1, -1]
resistances: "[Some Link
```
and the second group (the path) would match:
```
note.md
```
This commit changes the regex so that it doesn't falsely match in these cases and instead just matches the actual markdown link.
=> fix: Fix stringifier incorrectly matching some links

src/importers/Pathbuilder.d.ts, src/importers/PathbuilderImport.ts, src/importers/importer.worker.ts, src/importers/index.ts, src/importers/pf2eMonsterToolImport.ts, src/settings/settings.ts
Add the ability to import PCs (and NPCs) from [Pathbuilder2e](https://pathbuilder2e.com)
Fixes - #448 
The intent here is to have a quick reference for the GM for all the shenanigans that a Player gets up to, so the emphasis has been on listing and linking all feats, spells and items. 
Pathbuilder makes no distinction in its data structure between melee and ranged weapons. I have them all listed as 'Melee" because that's closer to a normal bestiary card, but was debating replacing that with the word "attack" or "weapon". 
I specify the json file as the source. Not sure if that's what you intended. I'm thinking that the next feature I want to add is to have the program prompt for a JSON id (a pathbuilder concept) and then the importer makes a restful API call to fetch the JSON without the …
=> feat: Initial implementation of pathbuilder import

index.ts, src/view/ui/Saves.svelte
Update skills and saves to accept/display traits as well (`name`/`desc`).
Ignore name fields that start with `_`.
```yaml
"saves":
- "intelligence": !!int "7"
- "charisma": !!int "5"
"skillsaves":
- "name": "[Deception](rules/skills.md#Deception)"
"desc": "+5"
- "name": "[Perception](rules/skills.md#Perception)"
"desc": "+4"
- "desc": "One of [Arcana](rules/skills.md#Arcana) +7, [History](rules/skills.md#History)\
\ +7, [Nature](rules/skills.md#Nature) +7, or [Religion](rules/skills.md#Religion)\
\ +7"
"condition_immunities": "[blinded](rules/conditions.md#Blinded), [charmed](rules/conditions.md#Charmed),\
\ [deafened](rules/conditions.md#Deafened), [exhaustion](rules/conditions.md#Exhaustion),\
\ [prone](rules/conditions.md#Prone)"
```
BEGIN_COMMIT_OVERRIDE
feat: Allow traits for `saves` …
=> ✨ allow traits for saves and skills

src/importers/PathbuilderImport.ts
The Pathbuilder2e importer gave all weapons the same name ("Melee"), which caused them to overwrite each other in the imported data so that only the last listed weapon was saved. This change uses the name of the weapon from the source data as the map key rather than the fixed string, so that all of the weapon attacks are listed in the output.
src/importers/PathbuilderImport.ts:199 - Use `weapon.name` instead of "Melee" for the trait name.
Possibly: **Abilities with duplicate names not showing up #483**, but I have not verified that.
BEGIN_COMMIT_OVERRIDE
fix: Fixes weapon name when using the pathfinder importer
END_COMMIT_OVERRIDE
=> Use weapon name instead of 'Melee' to prevent overwrite during import
